allowBuilds:
  '@google/genai': false
  esbuild: false
  protobufjs: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
minimumReleaseAgeExclude:
  - '@earendil-works/chord@0.99.1'
  - '@earendil-works/pi-agent-core@0.99.1'
  - '@earendil-works/pi-ai@0.99.1'
  - '@earendil-works/pi-codemode@0.99.1'
  - '@earendil-works/pi-coding-agent@0.99.1'
  - '@earendil-works/pi-mcp@0.99.1'
  - '@earendil-works/pi-telemetry@0.99.1'
  - '@earendil-works/pi-tui@0.99.1'
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
